package com.bookingsystem.application.invoice;

import com.bookingsystem.domain.booking.Booking;
import com.bookingsystem.domain.invoice.Invoice;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.io.ByteArrayOutputStream;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import org.springframework.stereotype.Component;

@Component
public class InvoicePdfGenerator {

	private static final DateTimeFormatter DATE_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
	private static final DateTimeFormatter INSTANT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")
			.withZone(ZoneOffset.UTC);

	public byte[] generate(Invoice invoice, Booking booking) {
		try {
			ByteArrayOutputStream out = new ByteArrayOutputStream();
			Document document = new Document();
			PdfWriter.getInstance(document, out);
			document.open();

			Font title = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
			Font body = FontFactory.getFont(FontFactory.HELVETICA, 11);
			Font bold = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);

			document.add(new Paragraph("Hold Invoice", title));
			document.add(new Paragraph(" "));
			document.add(new Paragraph("Invoice #" + invoice.getId(), bold));
			document.add(new Paragraph("Status: " + invoice.getStatus(), body));
			document.add(new Paragraph(
					"Amount: " + invoice.getAmount().toPlainString() + " " + invoice.getCurrency(),
					body));
			document.add(new Paragraph("Method: " + invoice.getMethod(), body));
			if (invoice.getPaidAt() != null) {
				document.add(new Paragraph("Paid at (UTC): " + INSTANT.format(invoice.getPaidAt()), body));
			}
			document.add(new Paragraph(" "));
			document.add(new Paragraph("Booking #" + booking.getId(), bold));
			document.add(new Paragraph("Resource: " + booking.getResourceId(), body));
			document.add(new Paragraph(
					"Window: "
							+ DATE_TIME.format(booking.getStartDate())
							+ " → "
							+ DATE_TIME.format(booking.getEndDate()),
					body));
			document.add(new Paragraph("Booking status: " + booking.getStatus(), body));
			document.add(new Paragraph(" "));
			document.add(new Paragraph(
					"Generated by Hold · receipt for your records",
					FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9)));

			document.close();
			return out.toByteArray();
		} catch (DocumentException ex) {
			throw new IllegalStateException("Failed to generate invoice PDF", ex);
		}
	}
}
